language: generic

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lua5.1
      - luarocks

cache:
  - apt

before_script:
  - luarocks --local install busted

script:
  - ~/.luarocks/bin/busted -v
