pipelines:
  automatic-lua-property-tables:
    group: defaultGroup
    locking: off
    materials:
      main_repo:
        git: https://github.com/d-led/automatic-lua-property-tables.git
        branch: master
    stages:
      - test:
          clean_workspace: false
          jobs:
            unit:
              resources:
                - lua
              tasks:
               - exec:
                   command: busted
                   arguments:
                     - -v
